# Generated by Django 3.2.3 on 2024-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240704_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True,
                                    upload_to='recipes/images/avatars'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True,
                                    upload_to='recipes/images/recipes'),
        ),
    ]
